name: tfgrid-ai-stack
version: 0.12.0-dev
description: AI-powered development platform with integrated Git hosting and deployment

# Pattern compatibility
patterns:
  recommended: tfgrid-ai-stack
  supported:
    - tfgrid-ai-stack

# Resource requirements
resources:
  cpu:
    min: 8
    recommended: 8
  memory:
    min: 16384
    recommended: 16384
  disk:
    min: 200
    recommended: 200
  ports:
    - 22:ssh
    - 80:http
    - 443:https
    - 3000:grafana
    - 9090:prometheus

# System dependencies
dependencies:
  system:
    - git
    - curl
    - wget
    - ansible
    - terraform
  external:
    - nodejs: ">=18.0.0"
    - npm: ">=9.0.0"

# Environment variables
environment:
  - name: DOMAIN
    required: false
    description: "Domain name for public access (leave empty for private mode)"

  - name: SSL_EMAIL
    required: false
    description: "Email for SSL certificate (required if domain set)"

  - name: API_RATE_LIMIT
    default: "100r/m"
    description: "API rate limit (requests per minute)"

  - name: BACKUP_RETENTION_DAYS
    default: "30"
    description: "Backup retention period in days"

  - name: BACKUP_SCHEDULE
    default: "0 2 * * *"
    description: "Backup cron schedule"

# Logging configuration
logging:
  method: systemd
  location: /var/log/tfgrid-ai-stack/

# Status check
status:
  method: http
  endpoint: "/api/v1/health"
  port: 3000

# App-specific commands
commands:
  create:
    script: scripts/create-project.sh
    description: "Create a new project with AI"
    args: "[description]"
    interactive: true

  projects:
    script: scripts/list-projects.sh
    description: "List all projects"

  monitor:
    script: scripts/monitor-project.sh
    description: "Monitor project logs"
    args: "[project-name]"
    interactive: true

  delete:
    script: scripts/delete-project.sh
    description: "Delete a project"
    args: "[project-name]"

  backup:
    script: scripts/manual-backup.sh
    description: "Trigger manual backup"

  restore:
    script: scripts/restore-backup.sh
    description: "Restore from backup"
    args: "[backup-file]"

# Documentation
documentation:
  readme: README.md
  architecture: ARCHITECTURE.md
  operations: OPERATIONS.md
  troubleshooting: docs/TROUBLESHOOTING.md

# Tags for discovery
tags:
  - ai
  - development
  - git
  - automation
  - monitoring
  - multi-vm

# Metadata
metadata:
  category: development
  maturity: beta
  support_level: official
  estimated_cost: high
  deployment_time: "10 minutes"
  complexity_level: advanced