name: tfgrid-ai-stack
version: 0.12.0-dev
description: AI-powered development platform with integrated Git hosting and deployment

# Pattern compatibility
patterns:
  recommended: single-vm
  supported:
    - single-vm

# Deployment hooks (called by deployer)
hooks:
  setup: deployment/setup.sh
  configure: deployment/configure.sh
  healthcheck: deployment/healthcheck.sh

# Single-VM pattern variables
variables:
  domain:
    type: string
    description: "Domain name for public access (leave empty for private mode)"
    default: ""
    required: false

  ssl_email:
    type: string
    description: "Email for SSL certificate (required if domain set)"
    default: ""
    required: false

  # Single-VM pattern specific variables
  vm_node:
    type: number
    description: "Node ID for VM deployment (auto-selected if 0)"
    default: 0
    required: false

  vm_cpu:
    type: number
    description: "VM CPU cores"
    default: 8
    required: false

  vm_memory:
    type: number
    description: "VM memory in MB"
    default: 16384
    required: false

  vm_disk:
    type: number
    description: "VM disk in GB"
    default: 200
    required: false

# Resource requirements
resources:
  cpu:
    min: 8
    recommended: 8
  memory:
    min: 16384
    recommended: 16384
  disk:
    min: 200
    recommended: 200
  ports:
    - 22:ssh
    - 80:http
    - 443:https
    - 3000:grafana
    - 9090:prometheus

# System dependencies
dependencies:
  system:
    - git
    - curl
    - wget
    - ansible
    - terraform
  external:
    - nodejs: ">=18.0.0"
    - npm: ">=9.0.0"

# Environment variables
environment:
  - name: DOMAIN
    required: false
    description: "Domain name for public access (leave empty for private mode)"

  - name: SSL_EMAIL
    required: false
    description: "Email for SSL certificate (required if domain set)"

  - name: API_RATE_LIMIT
    default: "100r/m"
    description: "API rate limit (requests per minute)"

  - name: BACKUP_RETENTION_DAYS
    default: "30"
    description: "Backup retention period in days"

  - name: BACKUP_SCHEDULE
    default: "0 2 * * *"
    description: "Backup cron schedule"

# Logging configuration
logging:
  method: systemd
  location: /var/log/tfgrid-ai-stack/

# Status check
status:
  method: http
  endpoint: "/api/v1/health"
  port: 3000

# App-specific commands
commands:
  launch:
    script: scripts/launch.sh
    description: "Open tfgrid-ai-stack web interface in browser"

  create:
    script: scripts/create-project.sh
    description: "Create a new project with AI"
    args: "[description]"
    interactive: true

  select-project:
    description: "Select active project for commands"
    args: "[project-name]"
    script: scripts/select-project.sh

  run:
    description: "Start AI agent loop for a project"
    args: "[project-name]"
    uses_context: active_project
    script: scripts/run-project.sh
    interactive: true

  monitor:
    description: "Monitor project progress"
    args: "[project-name]"
    uses_context: active_project
    script: scripts/monitor-project.sh
    interactive: true

  projects:
    description: "List all projects"
    script: scripts/list-projects.sh

  stop:
    description: "Stop AI agent for a project"
    args: "[project-name]"
    uses_context: active_project
    script: scripts/stop-project.sh

  delete:
    description: "Delete a project"
    args: "[project-name]"
    script: scripts/delete-project.sh

  login:
    description: "Authenticate with AI service"
    script: scripts/login.sh
    interactive: true

  status:
    description: "Show system status"
    script: scripts/status.sh

  projects:
    script: scripts/list-projects.sh
    description: "List all projects"

  monitor:
    script: scripts/monitor-project.sh
    description: "Monitor project logs"
    args: "[project-name]"
    interactive: true

  delete:
    script: scripts/delete-project.sh
    description: "Delete a project"
    args: "[project-name]"

  backup:
    script: scripts/manual-backup.sh
    description: "Trigger manual backup"

  restore:
    script: scripts/restore-backup.sh
    description: "Restore from backup"
    args: "[backup-file]"

# Documentation
documentation:
  readme: README.md
  architecture: ARCHITECTURE.md
  operations: OPERATIONS.md
  troubleshooting: docs/TROUBLESHOOTING.md

# Tags for discovery
tags:
  - ai
  - development
  - git
  - automation
  - monitoring
  - multi-vm

# Metadata
metadata:
  category: development
  maturity: beta
  support_level: official
  estimated_cost: high
  deployment_time: "10 minutes"
  complexity_level: advanced